# Site settings
name: Yubo Blog
email: yubo.qin@rutgers.edu
author: Yubo Qin
url: https://qybo1234.github.io/
resume_site: ""
github: https://github.com/qybo1234
baseurl: ""
description: Actually, less is more!
meta_description:
motto: It's our wits that make us men.
banner: 学而不思则罔，思而不学则殆。

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: qybo1234

